### ISSUE TITLE
Zoom not working on Docking page in ALCOR 40x20 and 60x30 MFDs

### ISSUE THREAD

**Issue by StoneBlue** [StoneBlue/ASET-Consolidated-Props#10]
Self explanatory....

This is at least with RPM.. MAS unknown, rn.

I'll test with MAS...

Will edit this, depending on whether its determined to be a *prop* issue, or RPM/MAS issue.

Note: FreeIVA, RevIVA & VesselViewer not installed.

**Comment by StoneBlue** [comment]
A little off-topic, but sort-of related...
Are all these seperate pages needed, or can something be combined?

ALCORDocking40x20.txt
ALCORDockingCam40x20.txt
ALCORDockingCross40x20.txt
ALCORDockingPortCam40x20.txt

60x30 MFD does not have/use as many different .txt overlays, for the Docking/Target page.. ??

**Comment by JonnyOThan** [comment]
It looks like the page does have zoom buttons hooked up.  I might have broken this on the RPM side.
