### ISSUE TITLE
CUSIOM_ASET_CHATTERER_ON error

### ISSUE THREAD

**Issue by JonnyOThan** [StoneBlue/ASET-Consolidated-Props#4]
10560 [ERR 20:33:18.380] [RasterPropMonitorComputer]: Unrecognized variable CUSIOM_ASET_CHATTERER_ON

Not sure where this is coming from

**Comment by StoneBlue** [comment]
Typo in:

/Instruments/TabloIndicator/Cautions/On_CHATTERER_ON

name = On_CHATTERER_ON

Fixed  & closed
